## M2 Lab

Below are a series of tasks to complete with PyTorch. In all problems, unless explicitly stated, you should use vectorized operations. This means you should not have any loops, list comprehensions, etc.

**Complete this section to reflect your group's attendance**

Group Members present the entire time:
- Person A
- Person B

Group Members absent the entire time:
- Person C

Group Members present for part of the time (add brief explanation of which parts):
- Person D (not present for questions 5-14)

#### Some sample tensors referenced later:

In [2]:
import torch
import numpy as np

In [3]:
a = torch.tensor(range(0,10))

b = torch.tensor([[11,12,13,14],
                  [21,22,23,24],
                  [31,32,33,34]], dtype=torch.int32)

c = torch.tensor([[[111, 112, 113, 114],
                   [121, 122, 123, 124]],

                  [[211, 212, 213, 214],
                   [221, 222, 223, 224]],

                  [[311, 312, 313, 314],
                   [321, 322, 323, 324]]], dtype=torch.int32)

### Part I: M1 Lab Revisited
The first 25 question are the same as those in the M1 Lab, except this time you must use torch operations acting upon torch tensors instead of numpy operations acting upon numpy ndarrays.

##### 1) Create a (2,2,2) tensor of all zeros, with type float32

(A solution is provided to this problem as an illustrative example.)

In [4]:
torch.zeros((2,2,2),dtype=torch.float32)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

##### 2) Create a (8,16) tensor where each element equals $\pi$, with type float32

(A solution is provided to this problem as an illustrative example.)

In [5]:
torch.full((8,16),torch.tensor(np.pi),dtype=torch.float32)

tensor([[3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
         3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
         3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
         3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
         3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
         3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
         3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
         3.1416, 3.1416, 3.1416, 3.14

##### 3) Check the dimensions of $a$ (okay to get a torch.Size object)

(A solution is provided to this problem as an illustrative example.)

In [6]:
a.shape

torch.Size([10])

#### 4) Test whether $a = a^T$ (superscript $T$ denotes transpose).

(A solution is provided to this problem as an illustrative example.)

In [7]:
torch.equal(a,a.T)

True

#### 5) Reshape $a$ into $(1,10)$.

In [8]:
torch.reshape(a, (1,10))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

#### 6) Test whether $a$ reshaped into $(1,10)$ equals $a$ reshaped into $(10,1)$.

In [9]:
torch.equal(torch.reshape(a, (1,10)), torch.reshape(a, (1,10)))

True

#### 7) Reshape c into a one-dimensional tensor, then sort it, then reshape it back to its original dimensions.

In [10]:
#torch.reshape(c.reshape((-1)), (3,2,4))
sorted, indices = torch.sort(c.reshape((-1))) 
torch.reshape(sorted,(3,2,4) )
#torch.reshape(torch.sort(c.reshape((-1))),(3,2,4))

tensor([[[111, 112, 113, 114],
         [121, 122, 123, 124]],

        [[211, 212, 213, 214],
         [221, 222, 223, 224]],

        [[311, 312, 313, 314],
         [321, 322, 323, 324]]], dtype=torch.int32)

#### 8) Compute the dot product of $a$ with itself (i.e., $\langle a,a \rangle$).

In [11]:
torch.dot(a,a)

tensor(285)

#### 9) Compute the Frobenius inner product of $b$ with itself (i.e., $\langle b,b \rangle$).

In [12]:
#element wise = torch.mul(A,A)
torch.mul(b,b).sum()

tensor(6890)

#### 10) Matrix multiply $b$ and $b^T$. Note that this is not element-wise multiplication; if you're hazy on matrix multiplication, check out https://en.wikipedia.org/wiki/Matrix_multiplication.

In [13]:
torch.mm(b, torch.transpose(b, 0, 1))

tensor([[ 630, 1130, 1630],
        [1130, 2030, 2930],
        [1630, 2930, 4230]], dtype=torch.int32)

#### 11) Test whether the shape of the matrix multiplication of $b$ and $b^T$ is the same as the shape of the matrix multiplication of $b^T$ and $b$.

In [14]:
torch.mm(b, torch.transpose(b, 0, 1)).shape == torch.mm(torch.transpose(b, 0, 1), b).shape

False

#### 12) Generate a (10000,1) tensor, where each element is random, drawn from a standard normal distribution with mean $\mu=1.5$ and standard deviation $\sigma=0.5$.

In [15]:
torch.empty(10000).normal_(mean = 1.5, std = 0.5)

tensor([1.5710, 1.7515, 1.5111,  ..., 0.9610, 2.0702, 1.6604])

#### 13) Generate the same tensor as in the previous problem, and then compute its standard deviation.

In [16]:
torch.empty(10000).normal_(mean = 1.5, std = 0.5).std()

tensor(0.5052)

#### 14) Index into b to extract the middle two columns of the second row.

In [17]:
b[1, 1:3]

tensor([22, 23], dtype=torch.int32)

#### 15) Write a function named last_element that takes an (n,m) tensor (assume type torch.float32) as input (should support arbitrary n and m) and returns the last column of the last row, via indexing.

In [18]:
def last_element(tenSir : torch.tensor) -> torch.float32 :
  return tenSir[-1, -1]

#last_element(b)

#### 16) Write a function named remove_outliers that takes an (n,) tensor with type torch.float32 (lets call it x) as input (should support arbitrary n), computes the mean $\mu$ and standard deviation $\sigma$ over all elements in x, clips all elements smaller than $\mu-\sigma$ to be $\mu-\sigma$, and clips all elements larger than $\mu+\sigma$ to be $\mu+\sigma$, and returns the result.

In [19]:
def remove_outliers(x : torch.tensor):
    mu = torch.mean(x)
    std = torch.std(x)

    return torch.clip(x, mu-std, mu+std)


#u = torch.empty(10000).normal_(mean = 1.5, std = 0.5) * 2

#remove_outliers(u)


#### 17) Write a function named all_positive that takes an arbitrary tensor (assume type torch.float32) as input and returns true if and only if all elements in the tensor are greater than 0.0. Note: the original tensor passed it must not be modified after this function has run; test to makes sure this is true. Note: the original tensor passed it must not be modified after this function has run; test to makes sure this is true.

In [20]:
def all_positive(x : torch.tensor):
    return (torch.min(x) > 0.0)

#all_positive(b)

#### 18) Write a function named leaky_relu that takes an arbitrary tensor (assume type torch.float32) as input, and multiplies all and only the negative values in the tensor by 0.01, and then returns the result (do not use torch's built-in LeakyReLU functionality).

In [21]:
def leaky_relu(x : torch.tensor):
    x[x < 0] = x[x < 0] * 0.01
    return x

#z = torch.empty(10).normal_(mean = 1.5, std = 0.5) * -2
#print(z)
#print(leaky_relu(z))

#### 19) The softmax function takes a tensor $x \in \mathbb{R}^N$ as input and returns $y \in \mathbb{R}^N$ as output according to the following equation.
$$ y_i = \frac{e^{x_i}}{\sum_{j=1}^N e^{x_j}} $$
Write a function softmax that takes an (n,) tensor x (assume type tensor.float32) as input and returns y, the softmax of it. You must do this using vectorized operations: no loops!  Do not use torch's built-in softmax functionality.

In [22]:
def softmax(x : torch.tensor):
    return torch.exp(x) / torch.sum(torch.exp(x))


#z = torch.empty(10).normal_(mean = 1.5, std = 0.5) * -2

#sm = torch.nn.Softmax(dim=0)

#print(z)
#print(sm(z))
#softmax(z)

#### 20) Write a function what_why that takes as input an arbitrary shape tensor, finds the element containing the smallest value, then finds the element containing the largest value, and then swaps those two elements and returns the result.  Note: the original tensor passed it must not be modified after this function has run; test to makes sure this is true.

In [23]:
def what_why(x : torch.tensor):
    tensir = torch.clone(x)
    minix, maxix = torch.argmin(tensir), torch.argmax(tensir)
    minimum, maximum = torch.min(tensir), torch.max(tensir)
    tensir[minix], tensir[maxix] = maximum, minimum
    return tensir

#print(a)
#print(what_why(a))
#print(a)

#### 21) Sum b column-wise (yielding a row vector).

In [24]:
torch.sum(b, axis=0)

tensor([63, 66, 69, 72])

#### 22) Compute the row-wise max of b.

In [25]:
torch.sum(b, axis=1)

tensor([ 50,  90, 130])

#### 23) Create a function column_norm that takes an arbitrary (n,m) tensor (of type torch.float32) and column-wise normalizes it (so that each column sums to 1). Note: the original tensor passed it must not be modified after this function has run; test to makes sure this is true. Reminder: no loops!

In [26]:
def column_norm(tenSir: torch.tensor) -> torch.tensor:
  return tenSir / torch.sum(tenSir,axis=0)

#print(b)
#print(column_norm(b))
#print(b)

#### 24) Reshape a into a (1,10), hstack it with itself, and compute the dimensions of the resulting tensor.

In [27]:
torch.hstack((torch.reshape(a, (1,10)), torch.reshape(a, (1,10)))).shape

torch.Size([1, 20])

#### 25) hsplit b into two matrices of equal size.

In [28]:
torch.split(b, 2, dim=1)



(tensor([[11, 12],
         [21, 22],
         [31, 32]], dtype=torch.int32), tensor([[13, 14],
         [23, 24],
         [33, 34]], dtype=torch.int32))

### Part II: Tensor View and Broadcasting Semantics

All students and all groups must complete the following problems.  Before you tackle them, please take a few minutes to read the following documents:

https://pytorch.org/docs/stable/tensor_view.html

https://pytorch.org/docs/stable/notes/broadcasting.html

#### 26) In the *text* box below, please briefly explain what a view of a tensor is and why views can be helpful.

A view is a copy of the tensor, but copied by reference. It is helpful for reshaping, slicing, and element-wise operations to tensors.

#### 27) In the *text* box below, please briefly explain what it means for a tensor to be contiguous, and what the contiguous() function does.

For a tensor to be contiguous, it means the tensor will view or modify the tensor in place, where as non-contiguous would treat it like a copy. Contiguous() allows us to make a copy of a non-continguous tensor that is contiguous.



#### 28) Give an example of using -1 as one of the dimensions in a call to reshape on b.

In [29]:
torch.reshape(b, (-1,))

tensor([11, 12, 13, 14, 21, 22, 23, 24, 31, 32, 33, 34], dtype=torch.int32)

#### 29) Check whether b is contiguous, then whether the transpose of b is contiguous, and then whether the transpose of the transpose of b is contiguous. Print each check, so your output should be three booleans in a row.

In [30]:
print(b.is_contiguous())
print(torch.transpose(b, 0, 1).is_contiguous())
print(torch.transpose(torch.transpose(b, 0, 1), 0, 1).is_contiguous())

True
False
True


#### 30) Use the permute function on b with the right arguments to produce a tensor that is equal to the transpose of b.




In [31]:
print(torch.transpose(b, 0,1))
print(b.permute(1,0))

tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33],
        [14, 24, 34]], dtype=torch.int32)
tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33],
        [14, 24, 34]], dtype=torch.int32)


#### 31) Generate a random (any flavor of random will do) tensor of $C \times N \times H \times W = 3 \times 100 \times 32 \times 32$. We will pretend this is a set of $N=100$ images, each $H=32$ pixels high and $W=32$ pixels wide, and each with $C=3$ color channels (red, green, blue). If we needed to feed this into a function that assumed the shape of the tensor was $(N,C,H,W)$, should you use view, reshape, tranpose or permute? In the text box below, please briefly explain which you should use and why. Then, in the code box below it, demonstrate its use to reorgnize the data so it is in the arrangment the function expects.

We decided to use view because we wanted to avoid uneccesary data copies, which helps us mitigate inefficient memory usage. We know that we're inputting a contiguous tensor, but it's unknown what the function itself will do, so if the function doesn't perform an operation that would make it non-contiguous, then the tensor will stay contiguous throughout the function.

In [32]:
x = torch.empty((3, 100, 32, 32)).normal_(mean = 1.5, std = 0.5)
print(x.shape)
print(x.view((100, 3, 32, 32)).shape)
print(x.shape)

torch.Size([3, 100, 32, 32])
torch.Size([100, 3, 32, 32])
torch.Size([3, 100, 32, 32])


#### 32) Generate the same random $C \times N \times H \times W = 3 \times 100 \times 32 \times 32$ tensor as in the previous problem. This time we want to feed this into a model that assumes each image is stacked into one long vector (i.e. each image is stacked into a long [length 3072] vector). Demonstrate the operation, or series of operations, needed to create the $(100,3072)$ matrix of flattened images. Note that your operations are incorrect if information from one image leaks into another: the $i$th row of the result should contain all and only the RGB pixel intensities for the $i$th image.

In [33]:
x = torch.empty((3, 100, 32, 32)).normal_(mean = 1.5, std = 0.5)
print(x.shape)
print(x.view((100, 3072)).shape)
print(x.shape)
print(x.view((100, 3, 32, 32))[0].sum())
print(x.view((100, 3072))[0].sum())

torch.Size([3, 100, 32, 32])
torch.Size([100, 3072])
torch.Size([3, 100, 32, 32])
tensor(4623.5283)
tensor(4623.5283)


#### 33) In the text box below it, explain what broadcasting is taking place  happenening in the following code box.


In [34]:
b + torch.tensor([1,2,3,4])
print(b)
print(b + torch.tensor([1,2,3,4]))

tensor([[11, 12, 13, 14],
        [21, 22, 23, 24],
        [31, 32, 33, 34]], dtype=torch.int32)
tensor([[12, 14, 16, 18],
        [22, 24, 26, 28],
        [32, 34, 36, 38]])


The broadcasting allows us to apply the operations of uneven sizes to all elements in a given tensor, all rows, or all columns. In this case the broadcasting applys the row addition to all rows of b. 

#### 34) In the text box below it, explain what broadcasting is taking place in the following code box? Also, why did I put transposes there? Why couldn't I just to b + torch.tensor([1,2,3])?

In [36]:
(b.T + torch.tensor([1,2,3])).T

tensor([[12, 13, 14, 15],
        [23, 24, 25, 26],
        [34, 35, 36, 37]])

The broadcasting here is very similar to above, but with the transpose operations we are broadcasting across the columns instead of the rows. If you did "b + torch.tensor([1,2,3])" then you would get a dimension mismatch as it would try to broadcast across the rows of size 4, rather than the columns of size 3. 

#### 35) In the text box below it, explain each of the following three torch.equal results. Why are the equal things equal, and the unequal things unequal?


In [42]:
z = torch.randn(10,1)
print(torch.equal(z @ z.T,z * z.T))
print(torch.equal(z.T @ z,z.T * z))
print(torch.equal(z.T * z,z * z.T))
#print(z)
#print(z.T)
#print(z.T @ z)
#print(z.T * z)


True
False
True


When using matrix multiplication the dimensions of the two input matrices determines the size of the output matrix. In the case of the "\*" operation python is attempting to broadcast the multiplication operation between the two matrices.  In the case where `z.T @ z != z.T * z` we see this effect as the output shape of `z.T @ z` is a 1x1 while `z.T * z` is a 10x10. In the case where some of these are equal to each other it holds the same properties as described before, just in the case that the dimensions of the result end up being the same.